/// Enum representing different types of IceWM menu entries
enum EntryType { prog, menu, separator, restart, quit }

/// Base class representing any IceWM menu entry
abstract class IceMenuEntry {
  String get label;
  String get icon;
  EntryType get type;
  bool get isGenerated;
  bool get isVisible;
}

/// Represents a program entry in IceWM menu
/// Format: prog "Name" "icon" "command"
class IceProgram implements IceMenuEntry {
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceProgram &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          icon == other.icon &&
          command == other.command &&
          isGenerated == other.isGenerated &&
          isVisible == other.isVisible;

  @override
  int get hashCode =>
      label.hashCode ^
      icon.hashCode ^
      command.hashCode ^
      isGenerated.hashCode ^
      isVisible.hashCode;
  @override
  final String label;
  @override
  final String icon;
  @override
  final EntryType type = EntryType.prog;
  
  /// The command to execute when this program is selected
  final String command;

  /// Whether this entry was generated by scanning (true) or created by user (false)
  @override
  final bool isGenerated;

  /// Whether this entry is visible in the menu
  @override
  final bool isVisible;

  IceProgram({
    required this.label,
    required this.icon,
    required this.command,
    this.isGenerated = false,
    this.isVisible = true,
  });

  /// Create a copy with optional field overrides
  IceProgram copyWith({
    String? label,
    String? icon,
    String? command,
    bool? isGenerated,
    bool? isVisible,
  }) {
    return IceProgram(
      label: label ?? this.label,
      icon: icon ?? this.icon,
      command: command ?? this.command,
      isGenerated: isGenerated ?? this.isGenerated,
      isVisible: isVisible ?? this.isVisible,
    );
  }
}

/// Represents a submenu entry in IceWM menu
/// Format: menu "Name" "icon" { ... }
class IceSubMenu implements IceMenuEntry {
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceSubMenu &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          icon == other.icon &&
          isGenerated == other.isGenerated &&
          isVisible == other.isVisible;

  @override
  int get hashCode =>
      label.hashCode ^
      icon.hashCode ^
      isGenerated.hashCode ^
      isVisible.hashCode;
  @override
  final String label;
  @override
  final String icon;
  @override
  final EntryType type = EntryType.menu;
  
  /// Child entries (programs, separators, or nested submenus)
  final List<IceMenuEntry> children;

  /// Whether this entry was generated by scanning (true) or created by user (false)
  @override
  final bool isGenerated;

  /// Whether this entry is visible in the menu
  @override
  final bool isVisible;

  IceSubMenu({
    required this.label,
    required this.icon,
    List<IceMenuEntry>? children,
    this.isGenerated = false,
    this.isVisible = true,
  }) : children = children ?? [];

  /// Add a child entry
  void addChild(IceMenuEntry entry) {
    children.add(entry);
  }

  /// Remove a child entry
  void removeChild(IceMenuEntry entry) {
    children.remove(entry);
  }

  /// Create a copy with optional field overrides
  IceSubMenu copyWith({
    String? label,
    String? icon,
    List<IceMenuEntry>? children,
    bool? isGenerated,
    bool? isVisible,
  }) {
    return IceSubMenu(
      label: label ?? this.label,
      icon: icon ?? this.icon,
      children: children ?? List.from(this.children),
      isGenerated: isGenerated ?? this.isGenerated,
      isVisible: isVisible ?? this.isVisible,
    );
  }
}

/// Represents a separator line in IceWM menu
/// Format: separator
class IceSeparator implements IceMenuEntry {
  @override
  final String label = '';
  @override
  final String icon = '';
  @override
  final EntryType type = EntryType.separator;
  @override
  final bool isGenerated = false;
  @override
  final bool isVisible = true;
}

/// Represents a restart entry in IceWM menu
/// Restarts the IceWM window manager
/// Format: restart
class IceRestart implements IceMenuEntry {
  @override
  final String label = 'Restart';
  @override
  final String icon = '';
  @override
  final EntryType type = EntryType.restart;
  @override
  final bool isGenerated = false;
  @override
  final bool isVisible = true;
}

/// Represents a quit entry in IceWM menu
/// Exits the IceWM window manager
/// Format: quit
class IceQuit implements IceMenuEntry {
  @override
  final String label = 'Quit';
  @override
  final String icon = '';
  @override
  final EntryType type = EntryType.quit;
  @override
  final bool isGenerated = false;
  @override
  final bool isVisible = true;
}
