import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'models/ice_entry.dart';
import 'parser.dart';
import 'writer.dart';
import 'widgets/menu_tree.dart';
import 'widgets/entry_editor.dart';
import 'applications_scanner.dart';
import 'directories_scanner.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IceWM Menuator',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const MenuEditorPage(),
    );
  }
}

class MenuEditorPage extends StatefulWidget {
  const MenuEditorPage({super.key});

  @override
  State<MenuEditorPage> createState() => _MenuEditorPageState();
}

class _MenuEditorPageState extends State<MenuEditorPage> {
  List<IceMenuEntry> _menuEntries = [];
  IceMenuEntry? _selectedEntry;
  bool _isLoading = true;
  String? _errorMessage;
  late File _menuFile;
  String _menuFilePath = '';
  bool _liveUpdateEnabled = false; // Live updates disabled by default
  Timer? _liveUpdateTimer; // Debounce timer for live updates
  
  @override
  void initState() {
    super.initState();
    _initializeMenuFile();
  }

  /// Initialize the menu file path and load its content
  Future<void> _initializeMenuFile() async {
    try {
      // Get home directory from environment or use path_provider
      final homeStr = Platform.environment['HOME'] ?? '';
      final homeDir = Directory(homeStr);

      final iceWmDir = Directory('${homeDir.path}/.icewm');

      // Ensure .icewm directory exists
      if (!await iceWmDir.exists()) {
        await iceWmDir.create(recursive: true);
      }

      _menuFile = File('${iceWmDir.path}/menu');
      _menuFilePath = _menuFile.path;

      // If the menu file doesn't exist, create a template
      if (!await _menuFile.exists()) {
        await _createTemplateMenu();
      }

      await _loadMenuFile();
    } catch (e) {
      setState(() {
        _errorMessage = 'Error loading menu file: $e';
        _isLoading = false;
      });
    }
  }

  /// Load and parse the menu file
  Future<void> _loadMenuFile() async {
    try {
      final content = await _menuFile.readAsString();
      final entries = IceMenuParser.parse(content);

      setState(() {
        _menuEntries = entries;
        _isLoading = false;
        _errorMessage = null;
      });
    } catch (e) {
      setState(() {
        _errorMessage = 'Error parsing menu: $e';
        _isLoading = false;
      });
    }
  }

  /// Create a template menu file
  Future<void> _createTemplateMenu() async {
    final template = '''# IceWM Menu
# Generated by Menuator
# Place your menu entries here

menu "Applications" "/usr/share/pixmaps/folder.png" {
  prog "Firefox" "/usr/share/pixmaps/firefox.png" firefox
  prog "Terminal" "/usr/share/pixmaps/terminal.png" xterm
  separator
  prog "Text Editor" "/usr/share/pixmaps/text-editor.png" gedit
}

separator
restart
quit
''';
    await _menuFile.writeAsString(template);
  }

  /// Save menu file and reload IceWM (for live updates)
  Future<void> _saveAndReloadMenu() async {
    // Cancel any pending live update
    _liveUpdateTimer?.cancel();
    
    // Schedule a new live update with debouncing
    _liveUpdateTimer = Timer(const Duration(milliseconds: 500), () async {
      try {
        final content = IceMenuWriter.serialize(_menuEntries);
        await _menuFile.writeAsString(content);
        
        // Small delay before reloading
        await Future.delayed(const Duration(milliseconds: 200));
        await _reloadIceWMMenu();
      } catch (e) {
        // Silent failure for live updates - don't show error snackbar
        debugPrint('Live update failed: $e');
      }
    });
  }

  /// Save the current menu to file
  Future<void> _saveMenuFile() async {
    debugPrint('=== _saveMenuFile START ===');
    try {
      debugPrint('Step 1: Serializing menu entries...');
      final content = IceMenuWriter.serialize(_menuEntries);
      debugPrint('Step 2: Writing menu file to ${_menuFile.path}...');
      await _menuFile.writeAsString(content);
      debugPrint('Step 3: Menu file written successfully');

      debugPrint('Step 4: Saving applications files...');
      // Save applications files
      await ApplicationsScanner.saveApplications(_menuEntries);
      debugPrint('Step 5: Applications files saved successfully');

      debugPrint('Step 6: Saving directories files...');
      // Save directories files
      await DirectoriesScanner.saveDirectories(_menuEntries);
      debugPrint('Step 7: Directories files saved successfully');

      if (mounted) {
        debugPrint('Step 8: Showing success snackbar...');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Menu saved! Reloading IceWM...'),
            duration: const Duration(seconds: 3),
            action: SnackBarAction(
              label: 'Reload Now',
              onPressed: _reloadIceWMMenu,
            ),
          ),
        );
        
        debugPrint('Step 9: Auto-reloading IceWM menu...');
        // Auto-reload after a short delay
        await Future.delayed(const Duration(milliseconds: 500));
        await _reloadIceWMMenu();
        debugPrint('Step 10: IceWM menu reload completed');
      }
    } catch (e, stackTrace) {
      debugPrint('=== _saveMenuFile ERROR ===');
      debugPrint('Error: $e');
      debugPrint('Stack trace: $stackTrace');
      debugPrint('=== END ERROR ===');
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error saving menu: $e')),
        );
      }
    }
    debugPrint('=== _saveMenuFile END ===');
  }

  /// Reload IceWM's menu by sending HUP signal
  Future<void> _reloadIceWMMenu() async {
    if (!mounted) return;
    try {
      // Try to reload IceWM menu with HUP signal
      // The -x flag ensures it matches "icewm" exactly, ignoring "icewm_menuator"
      debugPrint('_reloadIceWMMenu: Sending HUP signal to icewm process...');
      final result = await Process.run('pkill', ['-HUP', '-x', 'icewm']);
      debugPrint('_reloadIceWMMenu: pkill exit code: ${result.exitCode}');
      
      if (result.exitCode == 0) {
        debugPrint('_reloadIceWMMenu: IceWM reloaded successfully');
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('IceWM menu reloaded!'),
              duration: Duration(seconds: 2),
            ),
          );
        }
      } else {
        debugPrint('_reloadIceWMMenu: IceWM not running or pkill failed: ${result.stderr}');
        // If pkill fails, just show success anyway (file was saved)
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Menu saved. (IceWM reload not available in this session)'),
              duration: Duration(seconds: 2),
            ),
          );
        }
      }
    } catch (e) {
      debugPrint('_reloadIceWMMenu: Failed to run pkill: $e');
      // Error reloading, but file was saved
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Menu saved. Manual reload needed: pkill -HUP -x icewm'),
            duration: const Duration(seconds: 3),
          ),
        );
      }
    }
  }

  /// Scan for desktop applications and add them to an "Other" directory
  Future<void> _scanApplications() async {
    try {
      setState(() => _isLoading = true);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Scanning applications...'),
            duration: Duration(seconds: 2),
          ),
        );
      }

      final otherMenu = await ApplicationsScanner.scanAndCreateOtherDirectory();
      final existingCommands = _getExistingCommands();

      // Filter out applications that already exist
      final filteredChildren = otherMenu.children.where((child) {
        if (child is IceProgram) {
          return !existingCommands.contains(child.command);
        }
        return true;
      }).toList();

      if (filteredChildren.isNotEmpty) {
        final newOtherMenu = IceSubMenu(
          label: otherMenu.label,
          icon: otherMenu.icon,
          isGenerated: true,
          children: filteredChildren,
        );

        setState(() {
          _menuEntries.insert(0, newOtherMenu);
        });

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Added ${filteredChildren.length} applications to "Other" directory'),
              duration: const Duration(seconds: 3),
            ),
          );
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('All applications already exist in menu'),
              duration: Duration(seconds: 2),
            ),
          );
        }
      }

      // Auto-save and reload
      if (_liveUpdateEnabled) {
        await _saveAndReloadMenu();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error scanning applications: $e')),
        );
      }
    } finally {
      setState(() => _isLoading = false);
    }
  }

  /// Scan for desktop directories and add them as empty menus
  Future<void> _scanDirectories() async {
    try {
      setState(() => _isLoading = true);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Scanning directories...'),
            duration: Duration(seconds: 2),
          ),
        );
      }

      final directories = await DirectoriesScanner.scanAndCreateDirectories();
      final existingSubmenuNames = _getExistingSubmenuNames();

      int addedDirs = 0;

      for (final dir in directories) {
        if (!existingSubmenuNames.contains(dir.label)) {
          setState(() {
            _menuEntries.insert(0, dir);
          });
          addedDirs++;
        }
      }

      if (mounted) {
        if (addedDirs > 0) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Added $addedDirs directories'),
              duration: const Duration(seconds: 3),
            ),
          );
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('All directories already exist in menu'),
              duration: Duration(seconds: 2),
            ),
          );
        }
      }

      // Auto-save and reload
      if (_liveUpdateEnabled) {
        await _saveAndReloadMenu();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error scanning directories: $e')),
        );
      }
    } finally {
      setState(() => _isLoading = false);
    }
  }

  /// Get all existing program commands to avoid duplicates
  Set<String> _getExistingCommands() {
    final commands = <String>{};
    _collectCommandsRecursive(_menuEntries, commands);
    return commands;
  }

  /// Recursively collect all program commands
  void _collectCommandsRecursive(List<IceMenuEntry> entries, Set<String> commands) {
    for (final entry in entries) {
      if (entry is IceProgram) {
        commands.add(entry.command);
      } else if (entry is IceSubMenu) {
        _collectCommandsRecursive(entry.children, commands);
      }
    }
  }

  /// Get all existing submenu names to avoid duplicates
  Set<String> _getExistingSubmenuNames() {
    final names = <String>{};
    _collectSubmenuNamesRecursive(_menuEntries, names);
    return names;
  }

  /// Recursively collect all submenu names
  void _collectSubmenuNamesRecursive(List<IceMenuEntry> entries, Set<String> names) {
    for (final entry in entries) {
      if (entry is IceSubMenu) {
        names.add(entry.label);
        _collectSubmenuNamesRecursive(entry.children, names);
      }
    }
  }

  /// Get all available submenus for moving entries
  List<IceSubMenu> _getAllSubmenus() {
    final submenus = <IceSubMenu>[];
    _collectSubmenusRecursive(_menuEntries, submenus);
    return submenus;
  }

  /// Recursively collect all submenus
  void _collectSubmenusRecursive(List<IceMenuEntry> entries, List<IceSubMenu> submenus) {
    for (final entry in entries) {
      if (entry is IceSubMenu) {
        submenus.add(entry);
        _collectSubmenusRecursive(entry.children, submenus);
      }
    }
  }

  /// Create a backup of the current menu
  Future<void> _createBackup() async {
    try {
      final backupFile = File('${_menuFile.path}.bak');
      await _menuFile.copy(backupFile.path);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Backup created: ~/.icewm/menu.bak'),
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating backup: $e')),
        );
      }
    }
  }

  /// Show confirmation dialog for reloading the menu file
  Future<void> _showReloadConfirmation() async {
    final result = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Reload Menu File'),
        content: const Text(
          'This will reload the menu file from disk, discarding any unsaved changes. '
          'Are you sure you want to continue?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            style: TextButton.styleFrom(foregroundColor: Colors.orange),
            child: const Text('Reload'),
          ),
        ],
      ),
    );

    if (result == true) {
      await _loadMenuFile();
    }
  }

  /// Show confirmation dialog for resetting the menu
  Future<void> _showResetConfirmation() async {
    final result = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Reset Menu'),
        content: const Text(
          'This will clear all menu entries and start from scratch. '
          'A backup will be created automatically. Continue?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Reset'),
          ),
        ],
      ),
    );

    if (result == true) {
      await _resetMenu();
    }
  }

  /// Reset the menu to empty state
  Future<void> _resetMenu() async {
    try {
      // Create backup first
      await _createBackup();

      setState(() {
        _menuEntries.clear();
        _selectedEntry = null;
      });

      // Save empty menu
      await _saveAndReloadMenu();

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Menu reset. Backup saved as ~/.icewm/menu.bak'),
            duration: Duration(seconds: 3),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error resetting menu: $e')),
        );
      }
    }
  }

  /// Handle entry selection
  void _onEntrySelected(IceMenuEntry entry) {
    setState(() {
      // If clicking the same entry, deselect it
      if (_selectedEntry == entry) {
        _selectedEntry = null;
      } else {
        _selectedEntry = entry;
      }
    });
  }

  /// Handle entry update
  void _onEntryUpdated(IceMenuEntry updatedEntry) {
    setState(() {
      _updateEntryRecursive(_menuEntries, _selectedEntry, updatedEntry);
      _selectedEntry = updatedEntry;
    });

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Recursively find and update an entry
  void _updateEntryRecursive(
    List<IceMenuEntry> entries,
    IceMenuEntry? targetEntry,
    IceMenuEntry updatedEntry,
  ) {
    for (int i = 0; i < entries.length; i++) {
      if (entries[i] == targetEntry) {
        entries[i] = updatedEntry;
        return;
      }

      if (entries[i] is IceSubMenu) {
        _updateEntryRecursive(
          (entries[i] as IceSubMenu).children,
          targetEntry,
          updatedEntry,
        );
      }
    }
  }

  /// Handle entry deletion
  void _onEntryDeleted(IceMenuEntry entry) {
    if (entry.isGenerated) {
      // Hide generated entries instead of deleting them
      setState(() {
        _hideEntryRecursive(_menuEntries, entry);
        _selectedEntry = null;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Entry hidden')),
      );
    } else {
      // Delete user-created entries
      setState(() {
        _removeEntryRecursive(_menuEntries, entry);
        _selectedEntry = null;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Entry deleted')),
      );
    }

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Recursively hide an entry
  void _hideEntryRecursive(List<IceMenuEntry> entries, IceMenuEntry target) {
    for (int i = 0; i < entries.length; i++) {
      if (entries[i] == target) {
        if (entries[i] is IceProgram) {
          entries[i] = (entries[i] as IceProgram).copyWith(isVisible: false);
        } else if (entries[i] is IceSubMenu) {
          entries[i] = (entries[i] as IceSubMenu).copyWith(isVisible: false);
        }
        return;
      }

      if (entries[i] is IceSubMenu) {
        _hideEntryRecursive((entries[i] as IceSubMenu).children, target);
      }
    }
  }

  /// Handle entry unhiding
  void _onEntryUnhidden(IceMenuEntry entry) {
    setState(() {
      _unhideEntryRecursive(_menuEntries, entry);
      _selectedEntry = entry;
    });

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Entry unhidden')),
    );

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Recursively unhide an entry
  void _unhideEntryRecursive(List<IceMenuEntry> entries, IceMenuEntry target) {
    for (int i = 0; i < entries.length; i++) {
      if (entries[i] == target) {
        if (entries[i] is IceProgram) {
          entries[i] = (entries[i] as IceProgram).copyWith(isVisible: true);
        } else if (entries[i] is IceSubMenu) {
          entries[i] = (entries[i] as IceSubMenu).copyWith(isVisible: true);
        }
        return;
      }

      if (entries[i] is IceSubMenu) {
        _unhideEntryRecursive((entries[i] as IceSubMenu).children, target);
      }
    }
  }

  /// Recursively find and remove an entry
  void _removeEntryRecursive(List<IceMenuEntry> entries, IceMenuEntry target) {
    entries.removeWhere((entry) => entry == target);

    for (var entry in entries) {
      if (entry is IceSubMenu) {
        _removeEntryRecursive(entry.children, target);
      }
    }
  }

  /// Handle adding a new entry
  void _onAddEntry(EntryType type) {
    late IceMenuEntry newEntry;

    switch (type) {
      case EntryType.prog:
        newEntry = IceProgram(
          label: 'New Program',
          icon: '',
          command: '',
        );
        break;
      case EntryType.menu:
        newEntry = IceSubMenu(
          label: 'New Directory',
          icon: '',
        );
        break;
      case EntryType.separator:
        newEntry = IceSeparator();
        break;
      case EntryType.restart:
        newEntry = IceRestart();
        break;
      case EntryType.quit:
        newEntry = IceQuit();
        break;
    }

    setState(() {
      _menuEntries.add(newEntry);
      _selectedEntry = newEntry;
    });

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Entry added')),
    );

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Handle adding a new sub-directory to the currently selected directory
  void _onAddSubdirectory() {
    if (_selectedEntry is! IceSubMenu) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a Directory first')),
      );
      return;
    }

    final parent = _selectedEntry as IceSubMenu;
    final newSubdir = IceSubMenu(
      label: 'New Sub-Directory',
      icon: '',
    );

    setState(() {
      parent.children.add(newSubdir);
      _selectedEntry = newSubdir;
    });

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Sub-Directory added')),
    );

    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Handle dropping an entry into a submenu
  void _onEntryDropped(IceMenuEntry entry, IceSubMenu targetMenu) {
    setState(() {
      // Remove entry from current location
      _removeEntryRecursive(_menuEntries, entry);

      // Add entry to target menu
      targetMenu.children.add(entry);
      _selectedEntry = entry;
    });

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Moved to "${targetMenu.label}"'),
        duration: const Duration(seconds: 2),
      ),
    );

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Move entry up in the current menu
  void moveEntryUp(IceMenuEntry entry) {
    _moveEntryInList(_menuEntries, entry, -1);

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Move entry down in the current menu
  void moveEntryDown(IceMenuEntry entry) {
    _moveEntryInList(_menuEntries, entry, 1);

    // Live update: save and reload menu immediately
    if (_liveUpdateEnabled) {
      _saveAndReloadMenu();
    }
  }

  /// Move entry in a list by offset
  void _moveEntryInList(
    List<IceMenuEntry> entries,
    IceMenuEntry entry,
    int offset,
  ) {
    final index = entries.indexOf(entry);
    if (index >= 0) {
      if (index + offset >= 0 && index + offset < entries.length) {
        setState(() {
          entries.removeAt(index);
          entries.insert(index + offset, entry);
        });
      }
      return; // Found it, but could be at bounds
    }

    // Try to find and move in nested menus
    for (var e in entries) {
      if (e is IceSubMenu) {
        _moveEntryInList(e.children, entry, offset);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('IceWM Menuator'),
            if (_menuFilePath.isNotEmpty)
              Text(
                _menuFilePath,
                style: Theme.of(context).textTheme.labelSmall,
              ),
          ],
        ),
        elevation: 0,
        actions: [
          PopupMenuButton<String>(
            icon: const Icon(Icons.auto_awesome),
            tooltip: 'Scan Options',
            onSelected: _isLoading ? null : (value) {
              switch (value) {
                case 'applications':
                  _scanApplications();
                  break;
                case 'directories':
                  _scanDirectories();
                  break;
              }
            },
            itemBuilder: (context) => [
              const PopupMenuItem(
                value: 'applications',
                child: Text('Scan Applications'),
              ),
              const PopupMenuItem(
                value: 'directories',
                child: Text('Scan Directories'),
              ),
            ],
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            tooltip: 'Reset Menu',
            onPressed: _isLoading ? null : _showResetConfirmation,
          ),
          IconButton(
            icon: const Icon(Icons.flash_on),
            tooltip: _liveUpdateEnabled ? 'Disable Live Updates' : 'Enable Live Updates',
            onPressed: _isLoading ? null : () {
              setState(() {
                _liveUpdateEnabled = !_liveUpdateEnabled;
              });
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(_liveUpdateEnabled ? 'Live updates enabled' : 'Live updates disabled'),
                  duration: const Duration(seconds: 2),
                ),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.backup),
            tooltip: 'Create Backup',
            onPressed: _isLoading ? null : _createBackup,
          ),
          IconButton(
            icon: const Icon(Icons.save),
            tooltip: 'Save Menu',
            onPressed: _isLoading ? null : _saveMenuFile,
          ),
          IconButton(
            icon: const Icon(Icons.folder_open),
            tooltip: 'Reload Menu File',
            onPressed: _isLoading ? null : _showReloadConfirmation,
          ),
          IconButton(
            icon: const Icon(Icons.restart_alt),
            tooltip: 'Reload IceWM Menu',
            onPressed: _isLoading ? null : _reloadIceWMMenu,
          ),
        ],
      ),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    if (_isLoading) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 16),
            Text('Loading ~/.icewm/menu...'),
          ],
        ),
      );
    }

    if (_errorMessage != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.error_outline, size: 48, color: Colors.red),
            const SizedBox(height: 16),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 32.0),
              child: Text(
                _errorMessage!,
                textAlign: TextAlign.center,
                style: const TextStyle(fontSize: 14),
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton.icon(
              onPressed: _loadMenuFile,
              icon: const Icon(Icons.refresh),
              label: const Text('Retry'),
            ),
          ],
        ),
      );
    }

    if (_menuEntries.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.inbox, size: 48, color: Colors.grey),
            const SizedBox(height: 16),
            const Text('No menu entries found'),
            const SizedBox(height: 16),
            ElevatedButton.icon(
              onPressed: () => _onAddEntry(EntryType.prog),
              icon: const Icon(Icons.terminal),
              label: const Text('Add First Entry'),
            ),
          ],
        ),
      );
    }

    return Row(
      children: [
        // Left panel: Menu tree
        Expanded(
          flex: 2,
          child: Container(
            decoration: BoxDecoration(
              border: Border(
                right: BorderSide(
                  color: Theme.of(context).dividerColor,
                ),
              ),
            ),
            child: SingleChildScrollView(
              child: MenuTreeWidget(
                entries: _menuEntries,
                onEntrySelected: _onEntrySelected,
                onEntryDropped: _onEntryDropped,
                selectedEntry: _selectedEntry,
                onEntryUpdated: _onEntryUpdated,
              ),
            ),
          ),
        ),
        // Right panel: Entry editor
        Expanded(
          flex: 1,
          child: EntryEditorWidget(
            selectedEntry: _selectedEntry,
            onEntryUpdated: _onEntryUpdated,
            onEntryDeleted: _onEntryDeleted,
            onEntryUnhidden: _onEntryUnhidden,
            onAddEntry: _onAddEntry,
            onAddSubdirectory: _onAddSubdirectory,
            onMoveUp: (entry) {
              moveEntryUp(entry);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Moved up'),
                  duration: Duration(seconds: 1),
                ),
              );
            },
            onMoveDown: (entry) {
              moveEntryDown(entry);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Moved down'),
                  duration: Duration(seconds: 1),
                ),
              );
            },
            onClearSelection: () {
              setState(() {
                _selectedEntry = null;
              });
            },
            onMoveToSubmenu: (IceSubMenu submenu) {
              if (_selectedEntry != null) {
                _onEntryDropped(_selectedEntry!, submenu);
              }
            },
            availableSubmenus: _getAllSubmenus(),
          ),
        ),
      ],
    );
  }

  @override
  void dispose() {
    _liveUpdateTimer?.cancel();
    super.dispose();
  }
}
